export const TRANSACTIONS_LOADING = 'LOADING TRANSACTIONS';
export const SET_TRANSACTIONS = 'SETTING TRANSACTIONS IN STATE';
export const TRANSACTION_ERROR = 'ERROR GETTING TRANSACTIONS';
export const CLEAR_TRANSACTION_ERRORS = 'CLEARING TRANSACTION ERRORS';
